### ISSUE TITLE
Can you please help me setting up swayvnc in a docker environment. 

### ISSUE THREAD

**Issue by RajaMuneerBaigal** [bbusse/swayvnc#11]
I have installed swaywm on a docker alpine image and I want to access it remotely using swayvnc. I am new to sway and swayvnc. Can you help me set it up?  I am not even sure if its possible to use swayvnc in docker image.

**Comment by bbusse** [comment]
The container this repository builds shows that it can be done, did you try to run it?  
Check the README, podman is command line compatible to docker, just replace 'podman' with 'docker'
```
$ docker pull ghcr.io/bbusse/swayvnc:latest
```
Other than that, look at the Dockerfile for what is needed to achieve what you want: 
https://github.com/bbusse/swayvnc/blob/main/Dockerfile

**Comment by RajaMuneerBaigal** [comment]
This will pull swwayvnc image if I am not wrong. How can I run my custom alpine image with swaywm using this image. Thats the question

**Comment by bbusse** [comment]
Use the Dockerfile linked above as a base and add the changes you want, then build and run

**Comment by RajaMuneerBaigal** [comment]
Oka, I will give it a go. Will let you know if it works.

**Comment by bbusse** [comment]
You can also look at swayvnc-firefox for an example how to use swayvnc as a base image: 
https://github.com/bbusse/swayvnc-firefox/blob/main/Dockerfile  
swayvnc-firefox additionally runs firefox

**Comment by RajaMuneerBaigal** [comment]
I get these erros as I am not a user in your docker image and I don't have root privileges to install anything on it

ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

**Comment by RajaMuneerBaigal** [comment]
So what I am doing right now is using your images as a base and installing sway on it. and then want to see if sway works with swayvnc. But I guess to install anything on your docker image I need to be a root user or  a USER with sudo privileges

**Comment by bbusse** [comment]
sway is already installed: Check line 16 of the Dockerfile. There is a reason it's called 'swayvnc' (:

**Comment by RajaMuneerBaigal** [comment]
```   
docker run -e XDG_RUNTIME_DIR=/tmp                     -e WLR_BACKENDS=headless                     -e WLR_LIBINPUT_NO_DEVICES=1                     -e SWAYSOCK=/tmp/sway-ipc.sock                     -p 5900:5900                     -p 7023:7023   ghcr.io/bbusse/swayvnc
```

I used these commands to run your image. But I find some errors and sway doesn't launches.
```
0:00:00.001 [ERROR] [wlr] [render/wlr_renderer.c:322] drmGetDevices2 failed: No such file or directory
00:00:00.001 [ERROR] [wlr] [types/wlr_drm_lease_v1.c:705] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
00:00:00.010 [ERROR] [sway/config/output.c:808] execvp failed: No such file or directory
00:00:00.050 [ERROR] [wlr] [xwayland/server.c:443] Cannot find Xwayland binary "/usr/bin/Xwayland"
00:00:00.050 [ERROR] [sway/server.c:273] Failed to start Xwayland
ERROR: ../src/main.c: 1034: Failed to initialise DRM render node. No GPU acceleration will be available.
ERROR: ../src/main.c: 1034: Failed to initialise DRM render node. No GPU acceleration will be available.
```

**Comment by bbusse** [comment]
The errors are okay and not fatal for the operation. You should be able to connect with some vnc client and get output

**Comment by RajaMuneerBaigal** [comment]
I used remmina. but I can't get access to VNC Port at 0.0.0.0:5900
![image](https://user-images.githubusercontent.com/105891199/196232853-d36a7987-4af9-485e-a679-018b57e9c3a1.png)
what vnc viewer do I need to use?

**Comment by RajaMuneerBaigal** [comment]
![image](https://user-images.githubusercontent.com/105891199/196233009-9017c435-4c34-43a3-b45b-e4b3bdcb0049.png)
Here I can see it is running on port 5900 on local host but can't access it

**Comment by bbusse** [comment]
Please try with '-p${LISTEN_ADDRESS}:5910:5910' and then connect to 5910 instead of 5900

**Comment by bbusse** [comment]
I just tried with Remmina and port 5910, works for me

**Comment by RajaMuneerBaigal** [comment]
Oka let me see. But whats the output like. I can see a black screen on port 7023.

**Comment by RajaMuneerBaigal** [comment]
Bro, you are fantastic. I can use this image to install packages on it and can run sway in docker. :) Trust me you made my day. I was working on this for days. You saved me a lot of time at last.   
These three errors don't go in my code too. 
``` 
00:00:00.049 [wlr] [backend/wayland/backend.c:162] drmGetDeviceFromDevId failed: No such file or directory
00:00:00.049 [wlr] [render/wlr_renderer.c:322] drmGetDevices2 failed: No such file or directory
00:00:00.049 [wlr] [types/wlr_drm_lease_v1.c:705] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager


```
Anyhow, thank you for the help.

**Comment by bbusse** [comment]
Happy to help, I am glad it works!

**Comment by RajaMuneerBaigal** [comment]
I will try to add more packages to your docker file and build an image out of it now. And see if it works again with custom configuration. Thank you again you are awesome
