### ISSUE TITLE
Error "Operation Not Permitted" when the container tries to run sway

### ISSUE THREAD

**Issue by OmarKSH** [bbusse/swayvnc#13]
Hello,

I am getting a weird error when running the container.
I successfully built the container but when trying to run the container using ./run.sh i get this in the console
```
Using docker to run swayvnc-firefox
/entrypoint.sh: exec: line 13: sway: Operation not permitted
```

I tried checking the sway binary to check if it is the correct one, i even tried downloading it manually from https://github.com/bbusse/swayvnc-build/releases but i still get the same error

Just a note, I am trying to run the container on an aarch64 machine

**Comment by bbusse** [comment]
I can reproduce the issue, looking into it

**Comment by bbusse** [comment]
Please try now

**Comment by OmarKSH** [comment]
The container runs now but it reports a few errors
```
00:00:00.001 [ERROR] [wlr] [render/wlr_renderer.c:366] Failed to open '/dev/dri/renderD128': Permission denied
00:00:00.001 [ERROR] [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
00:00:00.009 [ERROR] [sway/config/output.c:817] execvp failed: No such file or directory
00:00:00.018 [ERROR] [wlr] [xwayland/server.c:442] Cannot find Xwayland binary "/usr/bin/Xwayland"
00:00:00.018 [ERROR] [sway/server.c:282] Failed to start Xwayland
Warning: ../src/output.c: 294: Output HEADLESS-1 power state failure
ERROR: ../src/ctl-server.c: 696: Another wayvnc process is already running.
ERROR: ../src/ctl-server.c: 697: Use the '-S' option to choose an alternate control socket location
```
I checked that the VNC port is open on the host (port 5910) and tried connecting to it but the client fails to connect to the server

**Comment by bbusse** [comment]
Try to set the LISTEN_ADDRESS in run.sh to something else and try to conntect to that address/port with vnc

**Comment by bbusse** [comment]
The other errors are not critical, like Xwayland not being around

**Comment by OmarKSH** [comment]
I tried setting the LISTEN_ADDRESS to 127.0.0.1 or an empty string but i still get the same error, but after removing the LISTEN_ADDRESS variable completely from the port mapping I can finally connect to the container using the VNC client
```
${executor} run -e XDG_RUNTIME_DIR=/tmp \
                -e WLR_BACKENDS=headless \
                -e WLR_LIBINPUT_NO_DEVICES=1 \
                -e WLR_RENDERER=pixman \
                -e SWAYSOCK=/tmp/sway-ipc.sock \
                -p5910:5910 \
                -p7000:7000 \
                -p7023:7023 \
                --privileged \
                ${CONTAINER}
```

There is still something wrong though, if I exit the container and try to run it again the connection from the VNC client fails.

I get one of these 2 errors when trying to run the container with the above setup
```
00:00:00.001 [ERROR] [wlr] [render/wlr_renderer.c:366] Failed to open '/dev/dri/renderD128': Permission denied
00:00:00.001 [ERROR] [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
00:00:00.008 [ERROR] [sway/config/output.c:817] execvp failed: No such file or directory
00:00:00.017 [ERROR] [wlr] [xwayland/server.c:442] Cannot find Xwayland binary "/usr/bin/Xwayland"
00:00:00.017 [ERROR] [sway/server.c:282] Failed to start Xwayland
Warning: ../src/output.c: 294: Output HEADLESS-1 power state failure
ERROR: ../src/ctl-server.c: 749: Failed to bind unix socket: Address in use
```
```
00:00:00.001 [ERROR] [wlr] [render/wlr_renderer.c:366] Failed to open '/dev/dri/renderD128': Permission denied
00:00:00.001 [ERROR] [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
00:00:00.008 [ERROR] [sway/config/output.c:817] execvp failed: No such file or directory
00:00:00.018 [ERROR] [wlr] [xwayland/server.c:442] Cannot find Xwayland binary "/usr/bin/Xwayland"
00:00:00.018 [ERROR] [sway/server.c:282] Failed to start Xwayland
Warning: ../src/output.c: 294: Output HEADLESS-1 power state failure
ERROR: ../src/ctl-server.c: 696: Another wayvnc process is already running.
ERROR: ../src/ctl-server.c: 697: Use the '-S' option to choose an alternate control socket location
```

**Comment by OmarKSH** [comment]
It seems like the issue happens only if i try running the container again right after exiting, if i wait a couple of seconds before running it again it seems to work, this is really weird

**Comment by bbusse** [comment]
I guess podman/conmon take some time to let hold off the sockets

**Comment by bbusse** [comment]
```
ERROR: ../src/ctl-server.c: 696: Another wayvnc process is already running.
ERROR: ../src/ctl-server.c: 697: Use the '-S' option to choose an alternate control socket location
```
Did you see this in swayvnc or swayvnc-firefox?

**Comment by bbusse** [comment]
Ok , so we actually accidentally do try start more than one instance

**Comment by bbusse** [comment]
https://github.com/bbusse/swayvnc/issues/14

**Comment by OmarKSH** [comment]
> ```
> ERROR: ../src/ctl-server.c: 696: Another wayvnc process is already running.
> ERROR: ../src/ctl-server.c: 697: Use the '-S' option to choose an alternate control socket location
> ```
> 
> Did you see this in swayvnc or swayvnc-firefox?

it happens in both
